[pytest]
pythonpath = .
testpaths = data_engineering/tests tests gis/tests satellite/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = WARNING